version: '3.8'

services:
  # PostgreSQL databases for each microservice
  postgres-races:
    image: postgres:15
    container_name: formula1-races-db
    environment:
      POSTGRES_DB: formula1_races
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_races_data:/var/lib/postgresql/data

  postgres-drivers:
    image: postgres:15
    container_name: formula1-drivers-db
    environment:
      POSTGRES_DB: formula1_drivers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_drivers_data:/var/lib/postgresql/data

  postgres-teams:
    image: postgres:15
    container_name: formula1-teams-db
    environment:
      POSTGRES_DB: formula1_teams
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_teams_data:/var/lib/postgresql/data

  postgres-tracks:
    image: postgres:15
    container_name: formula1-tracks-db
    environment:
      POSTGRES_DB: formula1_tracks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_tracks_data:/var/lib/postgresql/data

  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres-races
      - postgres-drivers
      - postgres-teams
      - postgres-tracks

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  # Races API
  races-api:
    build:
      context: ./races-api
      dockerfile: Dockerfile
    container_name: races-api
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres-races

  # Drivers API
  drivers-api:
    build:
      context: ./drivers-api
      dockerfile: Dockerfile
    container_name: drivers-api
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-drivers

  # Teams API
  teams-api:
    build:
      context: ./teams-api
      dockerfile: Dockerfile
    container_name: teams-api
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres-teams

  # Tracks API
  tracks-api:
    build:
      context: ./tracks-api
      dockerfile: Dockerfile
    container_name: tracks-api
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres-tracks

volumes:
  postgres_races_data:
  postgres_drivers_data:
  postgres_teams_data:
  postgres_tracks_data:
